SELECT * FROM DEPT;

SELECT ENAME || ','|| JOB AS EMPLOYEE_DETAILS , SAL FROM EMP;

SELECT ENAME, SAL FROM EMP WHERE SAL<=1500 OR SAL>=2850 ORDER BY ENAME;

SELECT ENAME, JOB, EMPNO FROM EMP WHERE EMPNO IN (7369,7499,3333);

SELECT ENAME FROM EMP WHERE ENAME LIKE '_A%';

SELECT ENAME,'*' || SAL, EMPNO FROM EMP WHERE ENAME LIKE '______';

